### ISSUE TITLE
How I  can use my own camera model instead of Ideal camera model

### ISSUE THREAD

**Issue by ForrestPi** [pupil-labs/pye3d-detector#42]
In the  code   of  readme
“camera = CameraModel(focal_length=561.5, resolution=[400, 400])”
But actually,  the camera needs calibration.
so how set a new Camera parameters after calibration and undistort  instead of  Ideal camera model

**Comment by papr** [comment]
Hi, pye3d does not take camera lens distortion into account. It only uses the focal length and camera resolution. Therefore, it is currently not possible to set other camera parameters than the two mentioned above.
