### ISSUE TITLE
Freeze eye sphere size

### ISSUE THREAD

**Issue by EyescannerJE** [pupil-labs/pye3d-detector#43]
Hi! @papr 
Is this the exact same 3d modes as the one used by Pupil Capture/Player?
I want to do pupillometry and look at how the pupil diameter reacts to light but then it is important that the eye-sphere size estimate does not change. In Pupil Capture/Player there is an option to freeze the model, can i freeze the model in pye3d as well?

**Comment by papr** [comment]
Hi @EyescannerJE 

Yes, Pupil Core software uses this repository under the hood. You can use [this property](https://github.com/pupil-labs/pye3d-detector/blob/master/pye3d/detector_3d.py#L159-L176) to freeze the detector internal models.
