### ISSUE TITLE
Can I obtain or install the **plsd** library for image generation?

### ISSUE THREAD

**Issue by zhaomengna-ylab** [pupil-labs/pye3d-detector#60]
Can I obtain or install the **plsd** library for image generation? I want to generate some test pictures.

**Comment by papr** [comment]
Hi, the `plsd` library is currently not available publicly. You can find a set of test pictures [here](https://github.com/pupil-labs/pye3d-detector/wiki/files/pye3d_test_input.npz). This is how you can [load the images from the file.](https://github.com/pupil-labs/pye3d-detector/blob/master/tests/integration/test_synthetic_metrics.py#L315-L320)
